Implementar Criação de Customer com Validações (Back-End)
EmilyFrade/mini-asaas pull request #23
Opened 2024-05-23 18:23 UTC by icarobteles

# Implementar Criação de Customer com Validações (Back-End)

## Descrição

Este PR adiciona a camada de serviço para criação de um Customer, com as devidas validações.

## Contexto

Faz parte do fluxo de funcionamento do Grails e é a camada responsável por controlar a comunicação entre Controllers e Domain Class...

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [ ] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [ ] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

As classes utilitárias criadas foram testadas e devem ser adicionados testes também para a classe de validação.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [x] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [x] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [ ] O PR possui capturas de tela ou gifs animados, se necessário.
- [x] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [ ] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

Não se aplica.

## Links úteis

Não se aplica.

## Informações adicionais

A camada de controller e visualização deve ser adicionada num outro PR, dependente deste, para divisão em partes menores.

2024-05-24 12:10 UTC, EmilyFrade commented on grails-app/i18n/messages.properties
> +future.birthDate=A data de aniversário não pode ser uma data futura.
```suggestion
future.birthDate=A data de nascimento não pode ser uma data futura.
```

2024-05-24 12:51 UTC, kmurilo commented on grails-app/services/com/mini/asaas/customer/CustomerService.groovy
> +    public Customer save(Map params) {
Aqui no service você já pode receber diretamente o adapter.

2024-05-24 12:51 UTC, kmurilo commented on grails-app/services/com/mini/asaas/customer/CustomerService.groovy
> +        Customer customer = new Customer()
Aqui a nomenclatura recomendada é essa:
```suggestion
        Customer validatedCustomer = new Customer()
```

2024-05-24 12:51 UTC, kmurilo commented on grails-app/services/com/mini/asaas/customer/CustomerService.groovy
> +    private Customer populateCustomer(Customer customer, CustomerAdapter customerAdapter) {
buildCustomer é uma nomenclatura mais próxima da que usamos.

2024-05-24 12:51 UTC, kmurilo commented on src/main/groovy/com/mini/asaas/customer/CustomerValidator.groovy
> +            if (todayMonthIsBeforeBirthMonth || (todayMonthIsEqualBirthMonth && todayDayIsBeforeBirthDay)) age--
Isso aqui pode ser aproveitado para calcular a diferença em anos entre duas datas .

2024-05-24 12:53 UTC, kmurilo commented on grails-app/services/com/mini/asaas/customer/CustomerService.groovy
> +        Customer customer = validateBeforeSave(customerAdapter)
```suggestion
        Customer customer = validate(customerAdapter)
```
Pode manter somente validate()

2024-05-24 12:57 UTC, kmurilo commented on grails-app/services/com/mini/asaas/customer/CustomerService.groovy
> +        customer.validate()
No momento do do .save() ja serã́o executadas as validações definidas na domain. Então não precisamos desta chamada.

2024-05-27 17:44 UTC, Yuri-Ferrari requested changes

2024-05-27 18:08 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/customer/CustomerValidator.groovy
> +    public CustomerValidator validateRequiredFields(Map requiredFields) {
Eu havia adicionado essa camada de validação de campos obrigatórios, mas depois decidimos que não era necessário por dois motivos: o front-end valida o envio de campos obrigatórios, mesmo que não seja tão seguro, e as constraints servem de dupla validação nesse contexto. Está de acordo? Se sim, removerei este método.

2024-05-27 18:29 UTC, Yuri-Ferrari approved these changes

2024-05-27 18:29 UTC, merged