Implementar criação do service de Payer com validações
EmilyFrade/mini-asaas pull request #24
Opened 2024-05-24 12:06 UTC by EmilyFrade

# Implementar criação do service de Payer com validações

## Descrição

Este PR adiciona a camada de serviço para criação de um Payer, com as devidas validações.

## Contexto

Faz parte do fluxo de funcionamento do Grails e é a camada responsável por controlar a comunicação entre Controllers e Domain Class...

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [ ] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [ ] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

Ainda serão criados os testes.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [ ] O PR possui capturas de tela ou gifs animados, se necessário.
- [x] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [ ] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

Não se aplica.

## Links úteis

Não se aplica.

## Informações adicionais

- A camada de controller e visualização deve ser adicionada num outro PR, dependente deste, para divisão em partes menores.
- Ainda será feita uma melhor validação do CEP informado pelo usuário.

2024-05-24 13:02 UTC, kmurilo commented on grails-app/service/com/mini/asaas/PayerService.groovy
> +        Payer payer = Payer.get(params.id as Long)
Aqui precisamos buscar um payer que não está deletado.

2024-05-24 18:03 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/utils/DateFormatUtils.groovy
>      public static Date format(String date) {
Minha sugestão é renomear os métodos que estão atualmente como format para algo como parseFromString e deixar o seu método displayFormat como format, faz mais sentido

2024-05-27 12:17 UTC, icarobteles requested changes

2024-05-27 12:17 UTC, icarobteles commented on grails-app/service/com/mini/asaas/payer/PayerService.groovy
> +        if(!payer.save()) throw new BusinessException(DomainErrorUtils.getFirstValidationMessage(payer))
Ao lançar um erro durante o ato de salvar o payer não é interessante que esse erro seja enviado como uma mensagem apropriada para o usuário, logo a sugestão é não utilizar a BusinessException aqui, pois ela deve ser utilizada para erros em que nós desejamos um feedback mais específico ao usuário.

Aqui basta executar payer.save(failOnError: true), caso ocorra algum erro, ele vai lançar uma exceção nesse ponto do código. Esta exceção será capturar pelo bloco catch (Exception e) do controller, exibindo uma mensagem de erro genérica ao usuário.

2024-05-27 14:23 UTC, EmilyFrade commented on src/main/groovy/com/mini/asaas/payer/PayerValidator.groovy
> +        if (birthDate > new Date()) {
No caso do pagador, pode ocorrer casos e fazer sentido permitir ser menor de idade, mas acho importante deixar essa informação salva.

2024-05-27 16:11 UTC, icarobteles approved these changes

2024-05-27 17:47 UTC, Yuri-Ferrari requested changes

2024-05-27 17:47 UTC, Yuri-Ferrari commented on grails-app/service/com/mini/asaas/payer/PayerService.groovy
> +    PayerRepository payerRepository
Não precisa instancionar direto no Service, instanciem dentro de cada método

2024-05-27 17:47 UTC, Yuri-Ferrari commented on grails-app/service/com/mini/asaas/payer/PayerService.groovy
> +                .validateZipCode(adapter.zipCode)
Mesmo comentário do PR do Customer, criem um método de validação dentro do validator e chamem apenas ele

2024-05-27 18:26 UTC, Yuri-Ferrari requested changes

2024-05-27 18:26 UTC, Yuri-Ferrari commented on src/main/groovy/com/mini/asaas/payer/PayerValidator.groovy
> +                .validateZipCode(adapter.zipCode)
Chama um método por linha, ao invés de encadeado pois fica mais legível

2024-05-27 18:38 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/repository/PayerRepository.groovy
> +        Payer payer = Payer.get(id)
Que tal de forma mais simplificada?

```suggestion
        return Payer.findByIdAndDeleted(id, false)
```

2024-05-27 18:47 UTC, EmilyFrade commented on src/main/groovy/com/mini/asaas/repository/PayerRepository.groovy
> +        Payer payer = Payer.get(id)
Na verdade estou considerando alterar esse método para buscar também os deletados e dependendo do resultado, exibir a possibilidade de editar ou restaurar o pagador.

2024-05-28 12:26 UTC, Yuri-Ferrari approved these changes

2024-05-28 12:26 UTC, merged