Possibilitar acessar pagador em caso de CPF-CNPJ/email igual
EmilyFrade/mini-asaas pull request #34
Opened 2024-05-29 12:46 UTC by EmilyFrade

# Possibilitar acessar pagador em caso de CPF-CNPJ/email igual

## Descrição

- Ao realizar o cadastro de pagador, em caso de CPF/CNPJ ou email igual a um já cadastrado, possibilita vizualizar ou restaurar pagador, caso esteja inativo.

## Contexto

As alterações melhoram a funcionalidade de validação e facilitam a usabilidade do usuário.

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [ ] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [ ] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

Não se aplica.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [x] O PR possui capturas de tela ou gifs animados, se necessário.
- [ ] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [ ] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

![restaurar-cadastro](https://github.com/EmilyFrade/mini-asaas/assets/82189395/06aef7b0-1b1a-4012-bb05-e3403980fb3c)

2024-05-29 16:20 UTC, icarobteles requested changes

2024-05-29 16:20 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/exceptions/BusinessException.groovy
> +    public BusinessException(String message, String code) {
Em todas as exceções desse tipo o código será necessário?
Caso não, eu sugiro que crie duas assinaturas de constructor, até para não quebrar os demais fluxos...

```suggestion
    public BusinessException(String message, String code) {...}
    public BusinessException(String message) {...}
```

2024-05-29 16:20 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payer/PayerValidator.groovy
>          if (!email.matches(EMAIL_REGEX)) {
Que tal utilizar os métodos em EmailUtils aqui para essa validação?

2024-05-29 18:22 UTC, icarobteles approved these changes

2024-05-29 18:31 UTC, Yuri-Ferrari approved these changes

2024-05-31 12:43 UTC, Yuri-Ferrari approved these changes

2024-05-31 12:43 UTC, merged