Implementar remoção e restauração de pagadores
EmilyFrade/mini-asaas pull request #35
Opened 2024-05-29 12:50 UTC by EmilyFrade

# Implementar remoção e restauração de pagadores

## Descrição

- Adiciona remover e restaurar às funcionalidades de pagadores;
- Altera a lista de pagadores para exibir também o CPF/CNPJ formatado;
- Cria página com lista de pagadores inativos (deletados);
- Altera o layout da sidebar;

## Contexto

São modificações necessárias para finalizar o CRUD de pagadores.

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [ ] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [X] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

Não se aplica.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [x] O PR possui capturas de tela ou gifs animados, se necessário.
- [ ] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [ ] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

<details>
<summary>Página atualizada com as funcionalidades</summary>  

![deletar-index](https://github.com/EmilyFrade/mini-asaas/assets/82189395/bd81035d-d281-45e7-935e-066616458457)
![deletar-detalhes](https://github.com/EmilyFrade/mini-asaas/assets/82189395/65a16d6b-ab82-44f2-8ecf-0738775fc033)
![restaurar-lista](https://github.com/EmilyFrade/mini-asaas/assets/82189395/b444b01e-214a-46b1-93e5-8ea646a68b01)

</details>

2024-05-29 16:28 UTC, icarobteles commented on grails-app/controllers/com/mini/asaas/payer/PayerController.groovy
> +            Payer payer = Payer.findByIdAndDeleted(id, false)
Aqui deveria utilizar o Repository, não?
E mais, que tal criar um método no service para ser o responsável por esta busca e lançar uma exceção caso a entidade não seja encontrada?

2024-05-29 16:28 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/utils/CpfCnpjUtils.groovy
> +        if (isCPF(cpfCnpj)) return "${cpfCnpj[0..2]}.${cpfCnpj[3..5]}.${cpfCnpj[6..8]}-${cpfCnpj[9..10]}"
Tem uma forma mais simples de fazer isso usando regex, o que acha?

```suggestion
        if (isCPF(cpfCnpj)) return cpfCnpj.replaceAll(/(\d{3})(\d{3})(\d{3})(\d{2})/, '$1.$2.$3-$4')
```

2024-05-29 17:25 UTC, EmilyFrade commented on grails-app/controllers/com/mini/asaas/payer/PayerController.groovy
> +            Payer payer = Payer.findByIdAndDeleted(id, false)
Acho que fica melhor, vou ajustar

2024-05-29 18:21 UTC, icarobteles approved these changes

2024-05-29 19:10 UTC, Yuri-Ferrari requested changes

2024-05-31 12:16 UTC, Yuri-Ferrari approved these changes

2024-05-31 12:16 UTC, Yuri-Ferrari commented
Conflitos

2024-05-31 12:43 UTC, Yuri-Ferrari approved these changes

2024-05-31 12:43 UTC, merged