Implementar relacionamento entre as entidades `Customer` e `User`
EmilyFrade/mini-asaas pull request #39
Opened 2024-05-31 17:35 UTC by icarobteles

# Implementar relacionamento entre as entidades `Customer` e `User`

## Descrição

Este PR adiciona o relacionamento entre as entidades `Customer` e `User`, de modo que 1 única conta (Customer) possa ter vários usuários (User) associados a ela.
Este PR também realiza alterações necessárias no fluxo de criação/edição de Customer, para fazer sentido tal relacionamento.

## Contexto

Esta mudança é necessária para satisfazer a necessidade do requisito sobre "Gestão de Multiusuários"

## Motivação

Link da tarefa no Jira: [Implementar relacionamento entre as entidades Customer e User](https://asaasdev.atlassian.net/browse/MINI-22?atlOrigin=eyJpIjoiNzFjYjAzMzYxMjA0NDZjYjg5YThmNjEwOGZlMDIzMWYiLCJwIjoiaiJ9)

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [ ] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [ ] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

Foi testado novamente o fluxo de cadastro e login, para certificar que tudo ocorre como esperado.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [x] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [ ] O PR possui capturas de tela ou gifs animados, se necessário.
- [ ] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [ ] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

Não se aplica.

## Links úteis

Não se aplica.

## Informações adicionais

Foram adicionadas/editadas algumas variáveis de ambiente, que foram devidamente atualizadas no arquivo de exemplo.

2024-05-31 17:43 UTC, EmilyFrade commented on grails-app/controllers/com/mini/asaas/customer/CustomerController.groovy
> +            e.printStackTrace()
Esqueceu de tirar

2024-05-31 19:25 UTC, Yuri-Ferrari requested changes

2024-05-31 19:25 UTC, Yuri-Ferrari commented on grails-app/services/com/mini/asaas/customer/CustomerService.groovy
> +        UserRole.create(user, Role.findByAuthority(UserFunction.ADMIN.getAuthority()))
Essa é uma regra de negócio de User, deve ficar no Service do User

2024-05-31 19:25 UTC, Yuri-Ferrari commented on grails-app/services/com/mini/asaas/customer/CustomerService.groovy
> +        }
Mesmo ponto do comentário acima

2024-06-03 12:12 UTC, EmilyFrade approved these changes

2024-06-03 13:16 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/user/UserFunction.groovy
> +enum UserFunction {
RoleAuthority nao fica melhor?

2024-06-03 13:16 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/user/UserFunction.groovy
> +
Podem remover essa linha em branco

2024-06-03 13:16 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/user/SaveUserAdapter.groovy
>          Map<String, String> params = Utils.normalizeParams(originalParams)
Podem me explicar o que faz?

2024-06-03 13:16 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/customer/CustomerAdapter.groovy
> +    String password
Estranho, a senha é sempre por usuário

2024-06-03 13:23 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/customer/CustomerAdapter.groovy
> +    String password
A ideia é que durante a criação de uma conta (Customer), um usuário padrão seja criado com o mesmo email que foi definido durante a etapa.
Então meio no método de save do Customer, também seja salvo um usuário admin com o mesmo email desse customer. Coloquei a senha aí para que viesse também no adapter, e fosse utilizada na parte de criar o usuário.

Mas entendi a observação. Talvez fosse melhor fazer assim?

No método save do CustomerController, receber os parâmetros, criar uma instância de CustomerAdapter, criar o customer normalmente, depois da criação bem sucedida, instanciar o SaveUserAdapter e criar o usuário. Assim separa melhor as coisas, confere?

2024-06-03 13:25 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        user.markDirty()
Estávamos com o comportamento de que ao alterar o valor de um atributo e salvar, não ocorria nenhum erro, porém as alterações não estavam sendo salvas no banco de dados. Parece que tem duas formas de solucionar esse problema, adicionando alguma configuração relacionada ao hibernate para habilitar esse dirty (hibernateDirtyChecking: true) ou utilizar o método markDirty para dizer explicitamente que ocorreu uma alteração.

2024-06-03 13:27 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        return user
Ok, nas alterações deste PR vou adotar esse estilo e depois vou criar uma tarefa para refatorar o projeto inteiro aplicando esses padrões nos demais.

2024-06-03 13:32 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/user/SaveUserAdapter.groovy
>          Map<String, String> params = Utils.normalizeParams(originalParams)
O normalizeParams no caso?
É um método que pega todos os parâmetros e caso tenha valor e seja do tipo String, realiza o trim para remover espaços em branco e depois retorna esse valor. Então a ideia é, como os params do Grails sempre vem como String, a ideia é apenas remover espaços em branco e aplicar nulo para params que não tiverem valor.

A execução desse método facilita e evita a repetição de realizar trim para strings ou verificar se é nulo ou fazer "as String" nos métodos que usamos em alguns adapters.

2024-06-03 13:32 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/user/UserFunction.groovy
> +enum UserFunction {
Concordo

2024-06-04 16:57 UTC, closed without merging

2024-06-04 16:58 UTC, icarobteles commented
Fechei este PR por envolver muitas alterações que não estão correlacionadas.

2024-06-05 15:13 UTC, welingtonloh commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        user.markDirty()
O hibernateDirtyChecking me parece melhor, exige menos codigo
Se esquecer o markDirty em alguma entidade, já ferraria