Atualizar `PayerService` para obter o Customer através da instância de User
EmilyFrade/mini-asaas pull request #40
Opened 2024-05-31 18:47 UTC by icarobteles

# Atualizar `PayerService` para obter o Customer através da instância de User

## Descrição

Este PR adiciona o carregamento dos Payer's a partir do Customer associado, que é carregado através do User autenticado na aplicação. Anteriormente, estava sendo feito de maneira explícita através de um campo id no formulário e a listagem dos pagadores estava retornando todos os pagadores, associados ou não ao Customer.

## Contexto

Esta mudança é necessária para prover mais segurança à aplicação, evitando que contas visualizassem pagadores associados a outras contas e cadastrasse pagadores em nomes de outras contas através do campo id.

## Motivação

Link da Tarefa no Jira: [Atualizar `PayerService` para obter o Customer através da instância de User](https://asaasdev.atlassian.net/browse/MINI-28?atlOrigin=eyJpIjoiMjI2ZmEyYWNlZDkyNGFhMGI0YWIwMWMyZTgwYzQ1OTkiLCJwIjoiaiJ9)

Este PR depende do PR #39 , pois utiliza do relacionamento provido para obter a instância do User e do Customer associado.

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [x] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [ ] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

Foi testado todo o fluxo de CRUD de um payer, agora com um usuário logado e devidamente associado à uma conta.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [ ] O PR possui capturas de tela ou gifs animados, se necessário.
- [ ] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [ ] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

Não se aplica.

## Links úteis

Não se aplica.

## Informações adicionais

Não se aplica.

2024-05-31 19:36 UTC, Yuri-Ferrari requested changes

2024-05-31 19:36 UTC, Yuri-Ferrari commented on grails-app/services/com/mini/asaas/payer/PayerService.groovy
> +        return (springSecurityService.loadCurrentUser() as User)?.customer
Esse método trata do Customer mas está no Service do Payer

2024-06-03 13:19 UTC, welingtonloh commented on grails-app/services/com/mini/asaas/payer/PayerService.groovy
> +
Isso vai abrir brecha para vcs criarem um método para cada tipo de filtragem que fizerem? não é o caminho

Pq não trabalham com um mapa de parametros sendo encaminhado ao Repository

Dentro do repository validam quais filtros receberam e devem ser aplicados

2024-06-03 13:42 UTC, icarobteles commented on grails-app/services/com/mini/asaas/payer/PayerService.groovy
> +
Vou estudar sobre isso e aplicar

2024-06-04 17:57 UTC, closed without merging

2024-06-04 17:57 UTC, icarobteles commented
Fechar este PR para implementar as alterações a partir das novas alterações que foram necessárias