Implementar a Classe de Domínio `Payment`
EmilyFrade/mini-asaas pull request #41
Opened 2024-06-03 15:11 UTC by EmilyFrade

# Implementar a Classe de Domínio `Payment`

## Descrição

Nesse PR foi criada a classe de domínio de Payment, que deve representar uma cobrança, a classe PaymentAdapter para transformar um map de parâmetros em valores compatíveis com os atributos de Payment, enums e labels relacionadas ao payment.

## Contexto

Essa alteração é necessária como escopo básico do projeto.

## Motivação

Essa alteração foi motivada pela necessidade do sistema em ter uma entidade para representar o Payment.

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [ ] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [ ] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

Não se aplica ainda.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [ ] O PR possui capturas de tela ou gifs animados, se necessário.
- [x] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [ ] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

Não se aplica.

## Links úteis

Não se aplica.

## Informações adicionais

Esta entidade deve ter uma relação direta com a entidade User, logo ela ainda sofrerá algumas alterações posteriormente.

2024-06-03 17:28 UTC, icarobteles requested changes

2024-06-03 17:28 UTC, icarobteles commented on grails-app/domain/com/mini/asaas/payment/Payment.groovy
> +        billingType blank: false, inList: BillingType.values().collect { it.toString() }
Nos demais enums utilizados até então, não estávamos adotando esse padrão, por que foi necessário aqui?

2024-06-03 17:28 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/BillingType.groovy
> +    public Boolean isValid() {
Esse método é realmente necessário? Ele está verificando se a instância de um dos valores do enum pertencem a lista dos valores possíveis para enum, não sei se faz sentido.

2024-06-03 17:28 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/BillingType.groovy
> +        return valueOf(type.toUpperCase())
Caso type seja nulo, o que ocorre? Aqui pode gerar uma `NullPointerException` e também uma `IllegalArgumentException`, sugiro que envolva num try/catch, retornando `null` caso caia em qualquer exceção, como já estamos fazendo nos demais enums:

```suggestion
        try {
            return valueOf(type.toUpperCase())
        } catch (Exception e) {
            return null
        }
```

2024-06-03 17:28 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/PaymentAdapter.groovy
> +        this.customer = params.customer as Customer
Se você pegar dos parâmetros normalizados, ocorrerá um problema. Caso o parâmetro não seja uma instância de String, ele será setado como null. Lembra que a ideia do normalizeParams é para trabalhar com os params que vem das páginas do grails.

Das duas uma, ou deixa aqui o Long customerID e Long payerId, ou pega esses valores diretos de originalParams. Tem que ver qual solução faz mais sentido:

```suggestion
        this.customer = originalParams.customer as Customer
        this.payer = originalParams.payer as Payer
```

ou 

 ```
 class PaymentAdapter {
     Long customerId
     
     Long payerId
     
     ...
     
     public PaymentAdapter(Map originalParams) {
            Map<String, String> params = Utils.normalizeParams(originalParams)
            if (!params) return
            this.customerId = params.customerId as Long
            this.payerId = params.payerId as Long
            ...
 }
 ```

2024-06-03 17:28 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/PaymentStatus.groovy
> +    public Boolean isValid() {
Aqui a mesma coisa do outro enum

2024-06-03 17:28 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/PaymentStatus.groovy
> +        return valueOf(status.toUpperCase())
```suggestion
        try {
            return valueOf(status.toUpperCase())        
        } catch (Exception e) {
            return null
        }

```

2024-06-03 17:28 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/PaymentAdapter.groovy
> +        this.originalValue = params.originalValue as BigDecimal
Que tal aplicar um remover não númericos (StringUtils.removeNonNumeric) para evitar qualquer tipo de problema durante o parse?

2024-06-03 17:28 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/PaymentAdapter.groovy
> +    Customer customer
Será que é interessante o Adapter carregar toda a instância de uma entidade ou melhor somente seu id?

2024-06-03 17:51 UTC, EmilyFrade commented on grails-app/domain/com/mini/asaas/payment/Payment.groovy
> +        billingType blank: false, inList: BillingType.values().collect { it.toString() }
Na verdade foi apenas uma validação a mais, considerando que ou outros enums tinham uma conversão ou utlizavam de labels, mas validei também no back, então não há necessidade, vou retirar

2024-06-03 17:56 UTC, EmilyFrade commented on src/main/groovy/com/mini/asaas/payment/BillingType.groovy
> +    public Boolean isValid() {
Foi o que método que utilizei para fazer a validação que comentei no back, mas é possível fazer de outras formas também caso não ache viável

2024-06-03 18:00 UTC, EmilyFrade commented on src/main/groovy/com/mini/asaas/payment/PaymentAdapter.groovy
> +        this.originalValue = params.originalValue as BigDecimal
Isso pode gerar problema com os pontos, não?

2024-06-03 19:10 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/PaymentAdapter.groovy
> +        this.originalValue = params.originalValue as BigDecimal
Realmente, realmente!

2024-06-03 19:18 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/payment/BillingType.groovy
> +    public Boolean isValid() {
Qual validação?

É que ao meu ver o método isValid na classe BillingType é redundante. A razão para isso é que o método isValid verifica se o valor do enum está contido na própria lista de valores do enum, o que é sempre verdadeiro, porque um enum só pode ter valores que foram definidos nele. Ou seja, qualquer instância de BillingType será necessariamente um dos valores definidos no enum. Entendeu meu ponto? 

Se o array de valores possíveis posse parcial, algo como o exemplo abaixo, aí faria sentido, pois poderíamos ter valores que não estavam no array, mas ainda assim seriam uma instância de BillingType.

```groovy
   public Boolean isBillingTypeWithCard() {
       return [CREDIT_CARD, DEBIT_CARD].contains(this)
   }
```

2024-06-04 12:07 UTC, EmilyFrade commented on src/main/groovy/com/mini/asaas/payment/BillingType.groovy
> +    public Boolean isValid() {
Agora entendi o que quis dizer, realmente não faz sentido

2024-06-04 12:09 UTC, EmilyFrade commented on src/main/groovy/com/mini/asaas/payment/PaymentAdapter.groovy
> +        this.originalValue = params.originalValue as BigDecimal
Nesse caso, estava dando problema com as vŕgulas, fiz algo parecido com o remover não numéricos para resolver

2024-06-04 12:30 UTC, icarobteles approved these changes

2024-06-05 12:45 UTC, EmilyFrade commented on src/main/groovy/com/mini/asaas/payment/PaymentAdapter.groovy
> +        this.interestValue = StringUtils.formatFromCommaToDot(params.interestValue) as BigDecimal
Entendo, agora que estou finalizando a parte de atualização percebi alguns problemas mesmo, incluindo nesse método de que formata de ponto para vírgula. Estou fazendo os ajustes, obrigada

2024-06-05 14:19 UTC, welingtonloh requested changes

2024-06-05 14:19 UTC, welingtonloh commented on grails-app/domain/com/mini/asaas/payment/Payment.groovy
> +    BigDecimal discountValue
Implementar somente o que está nos requisitos

2024-06-05 14:19 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/payment/BillingType.groovy
> +    BANKSLIP,
Deixa uma linha em branco sempre no inicio das classes

2024-06-05 14:19 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/payment/BillingType.groovy
> +    public static BillingType parseFromString(String type) {
```suggestion
    public static BillingType convert(type) {
```
Dessa forma vc pode receber String mesmo ou o proprio item da Enum

2024-06-05 14:19 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/payment/BillingType.groovy
> +        } catch (Exception e) {
```suggestion
        } catch (Exception exception) {
```
Não abreviem

2024-06-05 18:04 UTC, icarobteles approved these changes

2024-06-06 11:59 UTC, EmilyFrade commented on grails-app/domain/com/mini/asaas/payment/Payment.groovy
> +        paymentDate nullable: true
Manti as constraints, pois o Ícaro me alertou que não é blank por padrão.
https://docs.grails.org/6.1.2/ref/Constraints/blank.html

2024-06-06 22:09 UTC, welingtonloh commented on grails-app/domain/com/mini/asaas/payment/Payment.groovy
> +        paymentDate nullable: true
Show pela pesquisa, mas quero que vcs entendam que não é uma boa
Faz sentido ter ela nos campos String

Mas por exemplo customer, nós não vamos permitir um registro payment com customer nulo
Os que são objeto nao faz muito sentido
Os que são data tbm não
Parece que a aplicação estaria fazendo alguma loucura passando um string para esses campos, entendem?

2024-06-07 22:40 UTC, welingtonloh approved these changes

2024-06-07 22:42 UTC, welingtonloh approved these changes

2024-06-07 22:42 UTC, welingtonloh commented
Galera, nao consegui mergear esse
![image](https://github.com/EmilyFrade/mini-asaas/assets/13861122/51fcf508-c3f7-4b40-aa8b-bdac510b0150)

2024-06-10 12:10 UTC, icarobteles approved these changes

2024-06-10 12:10 UTC, merged

2024-06-10 12:12 UTC, icarobteles commented
Realizei o merge, pois o motivo do tech lead não ter conseguido fazer o merge para  main, foi pq ele fez um commit de merge com a base, o que fez com que se tornasse necessário uma aprovação de outra pessoa.