Implementar fluxo de atualizar dados básicos do usuário
EmilyFrade/mini-asaas pull request #45
Opened 2024-06-04 16:18 UTC by icarobteles

# Implementar fluxo de atualizar dados básicos do usuário

## Descrição

Este PR adiciona:

- UpdateUserAdapter para manipular os parâmetros de atualização
- Métodos para validação de dados no fluxo de atualizar um usuário
- Fluxo de atualizar os dados de um usuário (Front-End e Back-End)

## Contexto

É uma funcionalidade interessante para que o usuário possa atualizar seus dados.
Ainda deve haver uma outra funcionalidade à parte para alteração da senha do usuário.

## Depende de outro PR?

Sim, este PR depende do PR #44, pois aproveita algumas funcionalidades já implementadas nele.

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [x] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [ ] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

Não se aplica.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [x] O PR possui capturas de tela ou gifs animados, se necessário.
- [x] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [x] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

<details>
<summary>Página de Exibição/Atualização dos Dados do Usuário (Vendedor)</summary>  

![Screenshot from 2024-06-04 13-07-37](https://github.com/EmilyFrade/mini-asaas/assets/140961269/9092cf2f-7b06-411d-a071-6bf99340b0b2)

![Screenshot from 2024-06-04 13-07-45](https://github.com/EmilyFrade/mini-asaas/assets/140961269/44d802b3-abe0-47be-8b2d-d91418c6aafb)

</details>  

<details>
<summary>Página de Exibição/Atualização dos Dados do Usuário (Admin)</summary>  

![Screenshot from 2024-06-04 13-08-15](https://github.com/EmilyFrade/mini-asaas/assets/140961269/c17b3271-aff7-4fa4-9675-e336268f2cab)

</details>  

## Links úteis

Não se aplica.

## Informações adicionais

Não se aplica.

2024-06-04 18:25 UTC, EmilyFrade commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +            flash.section = "update"
Qual a função desse flash.section?

2024-06-04 18:25 UTC, EmilyFrade submitted a review, later dismissed

2024-06-04 18:27 UTC, icarobteles commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +            flash.section = "update"
Como dividi a tela dois <atlas-form-panel>, um para atualização de dados básicos e outro para atualização da senha, gostaria que as mensagens de erro respectivas aparecessem em determinadas seções, por ser algo simples e relacionado ao front que talvez mudaremos, não pensei numa solução mais elaborada, mas vale o questionamento.

2024-06-05 14:30 UTC, welingtonloh requested changes

2024-06-05 14:30 UTC, welingtonloh commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +        } catch (BusinessException e) {
abreviações

2024-06-05 14:30 UTC, welingtonloh commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +            flash.message = "Ocorreu um erro durante a atualização dos dados, aguarde um momento e tente novamente."
log.error

2024-06-05 14:30 UTC, welingtonloh commented on grails-app/views/user/show.gsp
> +<%@ page import="com.mini.asaas.user.RoleAuthority; com.mini.asaas.user.UserRole; com.mini.asaas.enums.address.AddressState; com.mini.asaas.utils.DateFormatUtils" %>
Um import por linha, fica mais legivel

2024-06-05 14:30 UTC, welingtonloh commented on src/main/groovy/com/mini/asaas/user/adapters/UpdateUserAdapter.groovy
> +
Linha em branco

2024-06-05 14:30 UTC, welingtonloh commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        userRoleService.assignAUserRole(adapter.roleAuthority, user)
userRoleService.save(user, roleAuthority) ja nao fica claro que o metodo faz?

2024-06-07 22:51 UTC, welingtonloh commented on grails-app/domain/com/mini/asaas/user/User.groovy
> +        return RoleAuthority.parseFromString(mainRole.authority.split("_")[1])
Achei bem ruim ter que esse metodo e esse split

Analisei o uso nesse PR, nao seria o caso de permitir selecionar multiplas roles para um usuario? select com multiple

2024-06-10 17:37 UTC, EmilyFrade approved these changes

2024-06-10 19:05 UTC, TuiNascimento commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +
linha sobrando
```suggestion
```

2024-06-10 19:05 UTC, TuiNascimento commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +    @Secured(["ROLE_ADMIN", "ROLE_SELLER"])
Se todas as actions desse controller tem as mesmas permissões, não vale colocar essa anotação direto no Controller?

2024-06-10 19:12 UTC, TuiNascimento commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        User user = show()
Ficou estranho chamar `show` aqui, não seria mais adequado um nome tipo "loadLoggedUser" ?

2024-06-10 22:00 UTC, TuiNascimento commented on grails-app/views/user/show.gsp
> +		</g:if>
Não entendi muito bem a ideia desse `flash.section`, não parece uma boa prática passar uma informação do tipo de ação que está sendo executada no flash.

Não faria sentido o atlas-alert ser renderizado apenas quando houver uma mensagem de fato?
```suggestion
		<g:if test="${flash.message}">
			<atlas-alert type="${flash.status}" message="${flash.message}"></atlas-alert>
		</g:if>
```

2024-06-10 22:11 UTC, TuiNascimento commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        User user = show()
Vi que isso é usado nos próximos PR's também. Pra não complicar a vida nos PR's que dependem desse, vamos seguir assim mas vale uma tarefa no backlog pra melhorar o nome desse método.

2024-06-12 12:55 UTC, TuiNascimento commented on grails-app/domain/com/mini/asaas/user/User.groovy
> +        adminUserRoles = adminUserRoles.stream().filter { it.user.customerId == this.customerId }.collect(Collectors.toList())
Se o sistema tiver 100.000 usuários, vamos carregar todos os 100k UserRoles de Admin aqui, pra daí filtrar em memória quais são do customer que queremos e só depois fazer a validação?

Não vale mais  a pena já trazer do banco de dados apenas os UserRoles com aquele Role E daquele Customer?

2024-06-12 13:33 UTC, icarobteles commented on grails-app/views/user/show.gsp
> +								${user.isAdminButNotUniqueAdminOfCustomer() ? "" : "disabled=''"}
Eu adicionei essa validação sim, no método `validateIfCanUpdateAuthority` de `UserValidator`. Se o usuário for o único admin da conta, vai dar erro ao tentar atualizar para outra função de usuário.

2024-06-12 13:34 UTC, icarobteles commented on grails-app/domain/com/mini/asaas/user/User.groovy
> +        adminUserRoles = adminUserRoles.stream().filter { it.user.customerId == this.customerId }.collect(Collectors.toList())
Concordo, implementei um `UserRoleRepository` e adicionei alguns filtros para poder fazer consultas mais assertivas.

2024-06-12 13:41 UTC, TuiNascimento commented on src/main/groovy/com/mini/asaas/user/UserValidator.groovy
> +        if (UserRoleRepository.query([customerId: user.customerId, onlyAdmin: true]).count() == 1) {
pq não usar o `isAdminButNotUniqueAdminOfCustomer`?

2024-06-12 13:47 UTC, TuiNascimento commented on src/main/groovy/com/mini/asaas/user/UserRoleRepository.groovy
> +            if (search.containsKey("onlyAdmin")) {
n entendi bem o nome desse flitro, ele não garante que é o único admin

2024-06-12 13:48 UTC, TuiNascimento commented on src/main/groovy/com/mini/asaas/user/UserRoleRepository.groovy
> +            if (search.containsKey("onlyAdmin")) {
não seria mais adequado o filtro ser algo como "roleAuthority", e receber via parâmetro a RoleAuthority que quer ser filtrada, nesse caso a ADMIN?

2024-06-12 13:50 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/user/UserValidator.groovy
> +        if (UserRoleRepository.query([customerId: user.customerId, onlyAdmin: true]).count() == 1) {
Eu queria deixar mais explícito, pois a função `isAdminButNotUniqueAdminOfCustomer` verifica duas condições: se é admin E se não é o único admin da conta. Porém, nesse caso da validação, para dar erro eu teria que negar isso, ou seja, só deveria dar erro se o usuário é admin e é o único admin da conta. Mas ao negar o método, ele poderia dar verdadeiro também no caso de usuário não ser admin.

Porém analisei melhor e essa verificação de usuário não ser admin eu já faço antes com um early return nesse método de validação, logo `!isAdminButNotUniqueAdminOfCustomer()` só retornaria verdadeiro realmente em casos de ser o único admin da conta.

Vou utilizar ele

2024-06-12 13:53 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/user/UserRoleRepository.groovy
> +            if (search.containsKey("onlyAdmin")) {
No caso vai buscar somente os registros que tiverem a role de admin

2024-06-12 13:55 UTC, icarobteles commented on src/main/groovy/com/mini/asaas/user/UserRoleRepository.groovy
> +            if (search.containsKey("onlyAdmin")) {
Indicaria um outro nome ou utilizar o filtro `roleAuthority` que já existe, daí passar explicitamente a role admin?

2024-06-12 14:05 UTC, TuiNascimento commented on src/main/groovy/com/mini/asaas/user/UserRoleRepository.groovy
> +            if (search.containsKey("onlyAdmin")) {
utilizar o filtro roleAuthority que já existe, daí passar explicitamente a role admin

2024-06-12 18:43 UTC, TuiNascimento approved these changes

2024-06-12 18:44 UTC, merged