Implementar fluxo de atualizar senha de um usuário
EmilyFrade/mini-asaas pull request #46
Opened 2024-06-04 16:36 UTC by icarobteles

# Implementar fluxo de atualizar senha de um usuário

## Descrição

Este PR adiciona:

- UpdateUserPasswordAdapter para lidar com os parâmetros de atualização de senha
- Método para validar os parâmetros de atualização de senha
- Funcionalidade de atualização de senha (Front-End e Back-End)

## Contexto

É uma funcionalidade que melhora a segurança e a experiência do usuário.

## Depende de algum PR?

Sim, este PR depende do PR #45. pois reaproveita a tela de visualização dos dados do usuário implementada nele.

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [ ] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [ ] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

Não se aplica.

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [x] O PR possui capturas de tela ou gifs animados, se necessário.
- [x] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [x] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

<details>
<summary>Alteração na Página de Visualização/Edição dos Dados de Usuário</summary>  

![Screenshot from 2024-06-04 13-26-55](https://github.com/EmilyFrade/mini-asaas/assets/140961269/d797c2f4-0f51-4b29-bb93-bcabaadaf1b9)

![Screenshot from 2024-06-04 13-29-37](https://github.com/EmilyFrade/mini-asaas/assets/140961269/ada2d0e8-80b6-44dc-9473-c2a0845c86d4)

![Screenshot from 2024-06-04 13-29-52](https://github.com/EmilyFrade/mini-asaas/assets/140961269/50371075-6118-442a-a904-d501fa08e8b5)

![Screenshot from 2024-06-04 13-30-11](https://github.com/EmilyFrade/mini-asaas/assets/140961269/a3b003cb-ebe3-442b-b8d8-9ac1c91d50f3)

</details>  

## Links úteis

Não se aplica.

## Informações adicionais

Não se aplica.

2024-06-04 18:32 UTC, EmilyFrade approved these changes

2024-06-05 14:46 UTC, welingtonloh requested changes

2024-06-05 14:46 UTC, welingtonloh commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        user.markDirty()
Isso aqui:
![image](https://github.com/EmilyFrade/mini-asaas/assets/13861122/658421c4-e38b-4bfe-8d61-a8ad49bfdd8e)

Deveria eliminar a necessidade desse markDirty

2024-06-05 14:46 UTC, welingtonloh commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +            e.printStackTrace()
abreviações e log.error

2024-06-05 14:46 UTC, welingtonloh commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        User user = show()
repository.get

2024-06-05 14:46 UTC, welingtonloh commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        if (user.hasErrors()) {
if (validatedUser.hasErrors()) throw new BusinessException(DomainErrorUtils.getFirstValidationMessage(user))

Como o throw funciona com um return, pode manter na mesma linha

2024-06-05 16:54 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        user.markDirty()
Abri um PR dedicado para esta solução: PR #49, ele deve ser priorizado, para depois atualizar estes PR's aqui.

2024-06-05 17:00 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        User user = show()
No caso estou obtendo o usuário logado, nesse caso poderia ser na verdade:

```suggestion
        User user = springSecurityService.loadCurrentUser() as User
```

Confere?

2024-06-07 17:27 UTC, EmilyFrade requested changes

2024-06-07 17:27 UTC, EmilyFrade commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        user.markDirty()
```suggestion

```

2024-06-07 22:52 UTC, welingtonloh approved these changes

2024-06-10 17:38 UTC, EmilyFrade approved these changes

2024-06-10 22:18 UTC, TuiNascimento approved these changes

2024-06-12 13:14 UTC, TuiNascimento commented on grails-app/services/com/mini/asaas/user/UserService.groovy
> +        if (user.hasErrors()) {
resolved?

2024-06-12 13:15 UTC, TuiNascimento commented on grails-app/views/user/show.gsp
> +		</g:if>
acredito que não é mais necessário né, pelo que entendi não seria mais usado esse esquema de section

2024-06-12 13:41 UTC, TuiNascimento approved these changes

2024-06-12 13:41 UTC, merged