Implementar cadastro de novos usuários
EmilyFrade/mini-asaas pull request #67
Opened 2024-06-13 14:07 UTC by EmilyFrade

# Implementar cadastro de novos usuários

## Descrição

Nesse PR foi implementada a funcionalidade de manipular diferentes usuários de um Customer, como cadastrar, listar, deletar e restaurar. Essas funcionalidades foram limitadas a usuários administradores. 

## Contexto

Essa mudança faz parte do domínio de user e o requisito de gestão multi usuário.

Esse PR depende do #66.

## Tipo de alteração

- [ ] Bug fix (alteração que corrige um problema)
- [x] Nova feature (alteração que adiciona funcionalidade)
- [ ] Refatoração (alteração que não corrige um bug e nem adiciona uma funcionalidade)
- [ ] Desempenho (alteração que melhora o desempenho)
- [ ] Dependência (alteração que adiciona ou remove uma dependência)
- [ ] Configuração (alteração que afeta a configuração)
- [ ] Manutenção (alteração que não adiciona funcionalidade e nem corrige um bug)
- [X] Estilização (alteração que afeta estilos CSS)
- [ ] Testes (alteração que adiciona ou modifica testes)
- [ ] Breaking change (correção ou recurso que faria com que a funcionalidade existente não funcionasse como esperado)
- [ ] Documentação (alteração ou adição de documentação)
- [ ] Outro (por favor, descreva)

## Como foi testado?

N/A

## Checklist de desenvolvimento

- [x] Meu código segue as diretrizes de estilo deste projeto.
- [x] Eu fiz uma revisão do meu próprio código.
- [x] Eu comentei meu código, principalmente em áreas difíceis de entender (caso necessário).
- [x] Eu fiz as alterações correspondentes na documentação.
- [x] Minhas alterações não geram novos avisos.
- [ ] Eu adicionei testes que provam que minha correção é eficaz ou que minha feature funciona.
- [ ] Testes unitários novos e existentes passam localmente com minhas alterações.
- [x] Eu verifiquei que minhas alterações funcionam em todas as plataformas suportadas.
- [ ] Se adicionei uma nova dependência, verifiquei se ela é compatível com o projeto.
- [ ] Se adicionei novas variáveis de ambiente, adicionei-as ao arquivo `.env.example`, sem adicionar valores sensíveis.

## Checklist de PR

- [x] O PR está no repositório correto.
- [x] O PR está sendo feito para a branch correta.
- [x] O PR segue o modelo de PR, disponível em [.github/pull_request_template.md](/.github/pull_request_template.md)
- [x] O PR possui um título significativo.
- [x] O PR possui uma descrição significativa, com contexto e motivação.
- [x] O PR possui capturas de tela ou gifs animados, se necessário.
- [ ] O PR possui labels conforme o tipo de alteração.
- [ ] O PR possui referências para issues ou tarefas relacionadas, se houver.
- [x] O PR possui referências para outros PRs relacionados, se houver.
- [x] O PR está atualizado com a branch de destino (verifique se há conflitos).

## Capturas de tela

<details>
<summary>CRUD - User</summary>  

![index](https://github.com/EmilyFrade/mini-asaas/assets/82189395/7042a254-c696-47b1-af48-3e208b273122)

![cadastro](https://github.com/EmilyFrade/mini-asaas/assets/82189395/1d69590d-d768-464b-8d59-6db0e3c8d0ee)

![delete_restore](https://github.com/EmilyFrade/mini-asaas/assets/82189395/69e00100-3009-4e16-af16-73175ce2567e)

![show](https://github.com/EmilyFrade/mini-asaas/assets/82189395/775f3582-5ea7-4a12-ab34-f02067fe76d1)

![only_admin](https://github.com/EmilyFrade/mini-asaas/assets/82189395/c418e849-6004-42b1-982a-ec617e8685b4)

</details>

## Links úteis

N/A

## Informações adicionais

N/A

2024-06-13 14:55 UTC, icarobteles requested changes

2024-06-13 14:55 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserAdminService.groovy
> +    private boolean hasOtherAdmins(Long customerId, Long userIdToExclude) {
Sempre wrapper's para deixar no padrão:

```suggestion
    private Boolean hasOtherAdmins(Long customerId, Long userIdToExclude) {
```

2024-06-13 14:55 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserAdminService.groovy
> +        List<User> userList = UserRepository.query([customerId: customerId]).list()
```suggestion
        return UserRoleRepository.query([customerId: customerId, roleAuthority: RoleAuthority.ADMIN.getAuthority]).count() > 1
```

OU

```suggestion
        User userToExclude = UserRepository.get(userIdToExclude)
        return userToExclude.isAdminButNotUniqueAdminOfCustomer()
```

2024-06-13 14:56 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserAdminService.groovy
> +        List<User> userList = UserRepository.query([customerId: customerId]).list()
Essa validação existe em um dos métodos de UserValidator, no meu PR #64 que já foi mergeado.

2024-06-13 16:16 UTC, EmilyFrade commented on grails-app/services/com/mini/asaas/user/UserAdminService.groovy
> +        List<User> userList = UserRepository.query([customerId: customerId]).list()
Não sabia, obrigada!!

2024-06-13 18:54 UTC, icarobteles requested changes

2024-06-13 18:54 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserAdminService.groovy
> +    private Boolean hasOtherAdmins(User userToExclude) {
Não é necessário esse método, uma vez que só é utilizado uma vez

2024-06-13 18:54 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserAdminService.groovy
> +        if (user.isAdmin() && !hasOtherAdmins(user)) {
```suggestion
        if (user.isAdmin() && !user.isAdminButNotUniqueAdminOfCustomer()) {
```

2024-06-14 01:58 UTC, TuiNascimento commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +            userService.update(new UpdateUserAdapter(params), user)
O que garante que se um Seller chamar esse endpoint passando o id de um User, ele não vai conseguir atualizar?
Mesma coisa para o `updatePassword`

2024-06-14 02:01 UTC, TuiNascimento commented on grails-app/services/com/mini/asaas/user/UserAdminService.groovy
> +        if (!user) throw new RuntimeException("Cobrança não encontrada")
```suggestion
        if (!user) throw new RuntimeException("Usuário não encontrado")
```

2024-06-14 12:44 UTC, EmilyFrade commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +            userService.update(new UpdateUserAdapter(params), user)
Faz sentido, obrigada

2024-06-14 12:45 UTC, icarobteles commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +            userService.update(new UpdateUserAdapter(params), user)
Seria mais interessante criar um updateOtherUser em UserAdminService, não?

2024-06-14 12:52 UTC, EmilyFrade commented on grails-app/controllers/com/mini/asaas/user/UserController.groovy
> +            userService.update(new UpdateUserAdapter(params), user)
Como é possível apenas verificar se o usuário é administrador, tem necessidade?

2024-06-17 11:54 UTC, icarobteles requested changes

2024-06-17 11:54 UTC, icarobteles commented on grails-app/services/com/mini/asaas/user/UserAdminService.groovy
> +    public User idAdminOfCustomer(Long id, User user) {
Esse nome não diz muita coisa sobre o que o método faz, concorda?

2024-06-17 12:52 UTC, icarobteles approved these changes

2024-06-18 12:08 UTC, merged